version: '2'

services:
  api:
    container_name: 'api-run'
    build: './api'
    ports:
      - '3000:3000'
    volumes:
      - './api:/go/src/github.com/GeoServer/project/api'
    environment:
      - DB_NAME=project
    depends_on:
      - 'mongo'
    links:
      - mongo:mongo
    networks:
      - samplenetwork

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - samplenetwork

networks:
  samplenetwork: